name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to 'main'
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Create .env File
        run: |
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
          echo "RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Site
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # ✅ Use Personal Access Token
          publish_dir: .output/public  # ✅ Correct path
          publish_branch: gh-pages  # ✅ Deploy to GitHub Pages
